### ISSUE TITLE
Tested devices

### ISSUE THREAD

**Issue by girlinterred** [MadTiger2409/Auto-Hid-Switch#1]
Tested your script found from the Prototype boards on Steam. Works flawlessly with the following devices on Windows 10 Home 64-bit

> Corsair K95 RGB Platinum (With Speed Switces)
> Logitech G502 Hero gaming mouse
> Logitech G933 wireless headset

Edit: typo

**Comment by MadTiger2409** [comment]
Oh, I didn't noticed that someone really took time to check it on his/her devices. Thank you for the feedback. I will add this to the list 😄
